# Generated by Django 3.0.7 on 2020-11-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20201101_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product_price',
            field=models.FloatField(null=True, verbose_name='цена продукта'),
        ),
    ]
